IF OBJECT_ID(N'dbo.Employee', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[Employee](
		[Id] [int] IDENTITY(1000,1) NOT NULL,
		[FirstName] [varchar](255) NULL,
		[MiddleName] [varchar](255) NULL,
		[LastName] [varchar](255) NULL,
	 CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]
END
GO